config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'

  get '/tasks/new', to: 'tasks#new', as: :new
  post '/tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_strong_params)
    redirect_to task_path(task)
  end

  def edit
  end

  def update
    @task.update(task_strong_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_strong_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id].to_i)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :details %> <br>
  <%= f.text_field :details %> <br>
  <%= f.check_box :completed %>
  <%= f.label :completed %> <br>
  <%= f.submit %>
<% end %>

<p> <%=link_to "Back to list", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |t| %>
  <% if t.completed? %>
    <input type="checkbox" checked>
  <% else %>
    <input type="checkbox">
  <% end %>
  <%=link_to t.title, task_path(t) %>
  <%=link_to "delete", destroy_path(t), method: :delete, data: { confirm: "delete #{t.title} ?" } %>
  <br>
<% end %>

<p> <%=link_to "+ Add new task", new_path %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :details %> <br>
  <%= f.text_field :details %> <br>
  <%= f.submit %>
<% end %>

<p> <%=link_to "Back to list", tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p> <%=link_to "Edit this task", edit_path %></p>

<p><%= @task.details %></p>

<% if @task.completed?%>
  <input type="checkbox" checked>
  <p>This task is completed</p>
<% else %>
  <input type="checkbox">
  <p>This task is not yet compeleted</p>
<% end %>

<p> <%=link_to "Back to list", tasks_path %></p>